### ISSUE TITLE
Make it Gatsby v3 compatible

### ISSUE THREAD

**Issue by cedricdelpoux** [Mike-Dax/gatsby-plugin-ffmpeg#21]
Hi, thank you for this plugin.
Unfortunately it does not work withGatsby v3 because `boundActionCreators` and `createJob` changed in v3.

The following line needs to be changed

`const { boundActionCreators } = require(`gatsby/dist/redux/actions`)`

**Comment by Mike-Dax** [comment]
The 0.4.x releases are Gatsby v3 compatible.
